### ISSUE TITLE
Initial support checklist

### ISSUE THREAD

**Issue by Beanow** [oneplus-karen-roms/android_device_oneplus_karen-twrp#1]
Based on https://twrp.me/faq/OfficialMaintainer.html:

## Blocking checks
- [x] Correct screen/recovery size
- [x] Working Touch, screen
- [x] Backup to internal (no microSD slot)
- [x] Restore from internal (no microSD slot)
- [x] reboot to system
- [x] ADB

## Medium checks
- [x] update.zip sideload
- [x] UI colors (red/blue inversions)
- [x] Screen goes off and on
- [x] F2FS/EXT4 Support, exFAT/NTFS where supported
- [x] all important partitions listed in mount/backup lists
- [x] backup/restore to/from external (USB-OTG) storage
- [ ] backup/restore to/from adb (https://gerrit.omnirom.org/#/c/15943/) _Fails, 0 byte file_
- [x] decrypt /data
- [x] Correct date

## Minor checks
- [x] MTP export
- [x] reboot to bootloader
- [x] reboot to recovery
- [x] poweroff
- [x] battery level
- [x] temperature
- [ ] encrypted backups (disabled, upstream TWRP issues seems like)
- [x] input devices via USB (USB-OTG) - keyboard, mouse and disks
- [ ] USB mass storage export
- [x] set brightness
- [x] vibrate
- [x] screenshot
- [ ] partition SD card (You can format an existing partition to fat32. You can't _partition_.)

**Comment by Beanow** [comment]
Currently known issues:
- Using `fastboot boot <image>` doesn't work, due to a very common MediaTek bootloader bug.
- The `/data` partition fails to back up, at least when populated by OxygenOS. Probably FBE related.
  ```
  [944:cat]PKCS#7 signature not signed with a trusted key
  [944:cat]fs-verity (dm-28, inode 28595): File's signing cert isn't in the fs-verity keyring
  ```
- Trying to install the stock "full" OTA zip fails. Because AOSP/TWRP `update_engine` considers that OTA invalid.
  Other zips, such as magisk modules, do work.
   ```
   update_engine_sideload E 10-09 19:46:33   748   748 [ERROR:delta_performer.cc(1128)] PartitionUpdate odm doesn't have a version field. Not allowed in partial updates.
  update_engine_sideload E 10-09 19:46:33   748   748 [ERROR:delta_performer.cc(1092)] Timestamp check returned ErrorCode::kDownloadManifestParseError
   ```
- With "Partition SD card" you can't select an OTG USB stick. Only _partitions on it_.
  Which you can format to fat32, but not partition.
  (In return, you get the ability to use any partition on the USB stick to store backups on)

**Comment by 0xSecureByte** [comment]
is there any way to prevent this to happen?





```
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:download_action.cc(84)] Marking new slot as unbootable
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:multi_range_http_fetcher.cc(45)] starting first transfer
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:multi_range_http_fetcher.cc(74)] starting transfer of range 2114+5477770252
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:delta_performer.cc(115)] Completed 0/? operations, 16384/5477770252 bytes downloaded (0%), overall progress 0%
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:delta_performer.cc(346)] Manifest size in payload matches expected value from Omaha
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:delta_performer.cc(1012)] Verifying using certificates: /system/etc/security/otacerts.zip
Step 1/2update_engine_sideload I 02-16 11:18:21   746   746 [INFO:delta_performer.cc(1049)] Detected a 'delta' payload.
update_engine_sideload E 02-16 11:18:21   746   746 [ERROR:delta_performer.cc(1128)] PartitionUpdate system_ext doesn't have a version field. Not allowed in partial updates.
update_engine_sideload E 02-16 11:18:21   746   746 [ERROR:delta_performer.cc(1092)] Timestamp check returned ErrorCode::kDownloadManifestParseError
update_engine_sideload E 02-16 11:18:21   746   746 [ERROR:download_action.cc(222)] Error ErrorCode::kDownloadManifestParseError (23) in DeltaPerformer's Write method when processing the received payload -- Terminating processing
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:delta_performer.cc(217)] Discarding 218724 unused downloaded bytes
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:multi_range_http_fetcher.cc(177)] Received transfer terminated.
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:multi_range_http_fetcher.cc(129)] TransferEnded w/ code 200
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:multi_range_http_fetcher.cc(131)] Terminating.
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:action_processor.cc(116)] ActionProcessor: finished DownloadAction with code ErrorCode::kDownloadManifestParseError
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:action_processor.cc(121)] ActionProcessor: Aborting processing due to failure.
update_engine_sideload I 02-16 11:18:21   746   746 [INFO:update_attempter_android.cc(546)] Processing Done.
update_engine_sideload E 02-16 11:18:21   746   746 snapshot.cpp:2425] Open failed: /metadata/ota: No such file or directory
Error applying update: 23 (ErrorCode::kDownloadManifestParseError)update_engine_sideload E 02-16 11:18:21   746   746 snapshot.cpp:2425] Open failed: /metadata/ota: No such file or directory
Updater process ended with ERROR: 1
```
